functions:
- route: "/api/fetch"
  url: "http://104.211.56.83:8089"
  accessToken: "string_token"
  type: "Splunk"
- route: "/api/fetch3"
  url: "http://104.211.56.83:8089"
  accessToken: "string_token"
  type: "Splunk"
- route: "/api/fetch4"
  url: "http://104.211.56.83:8089"
  accessToken: "string_token"
  type: "Splunk"  
- route: "/api/prometheus-5"
  url: "/api/fetch5"
  login: ""
  password: ""
  type: "Prometheus"